// Blog loader — reads `.md` files from `content/blog/`, parses frontmatter
// (YAML-lite via regex), and renders the body with `marked`.
//
// Design: zero deps besides `marked`. We keep post bodies short enough that
// a tiny parser is fine. Every post lives at `content/blog/{slug}.{lang}.md`
// where `{lang}` is `en`, `es`, or `pt`. This means a single slug can have up
// to 3 localized bodies; the listing/index pages group by slug and pick the
// right one based on the current locale (with fallback to `en`).

import { readdirSync, readFileSync, existsSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { marked } from 'marked';

export type BlogLocale = 'en' | 'es' | 'pt';

export interface BlogPostMeta {
  slug: string;
  title: string;
  description: string;
  date: string; // ISO yyyy-mm-dd
  tags: string[];
  readingTime: number; // minutes
  author: string;
  // Optional — populated by the news pipeline (autoblogging) when the
  // post has a cover image from Pexels. Kept optional so existing posts
  // (no cover) don't break.
  coverImage?: string;
  coverImageCredit?: string;
  coverImageAlt?: string;
  // Drafts (news pipeline output) are written with `draft: true` and live
  // in `content/blog/drafts/`. The listing pages only render published
  // posts (`draft: false` or missing), so a draft stays invisible until
  // Andrés promotes it to `content/blog/<slug>.<lang>.md` without the
  // draft flag.
  draft?: boolean;
  // Source attribution for news/opinion posts. Lets readers verify the
  // underlying story and protects against LLM hallucination (we always
  // link to the original).
  source?: string;
  sourceTitle?: string;
  // Provenance — which pipeline step produced this post. Useful for
  // auditing. `human` = hand-written, `news-pipeline-v1` = autogenerated.
  generatedBy?: string;
  // Relative path to the source file from repo root. Populated for
  // drafts (so the drafts UI can offer an "Open in editor" link) and
  // for published posts (for the same reason).
  draftPath?: string;
}

export interface BlogPost extends BlogPostMeta {
  content: string; // pre-rendered HTML from `marked`
  raw: string; // raw markdown (for OG / RSS / etc.)
  locale: BlogLocale;
}

export interface BlogPostSummary extends BlogPostMeta {
  href: string; // locale-prefixed path
  locale?: BlogLocale; // locale this summary was built for
}

const CONTENT_DIR = join(process.cwd(), 'content', 'blog');

// Configure marked once: GitHub-flavored breaks on, smart lists on,
// HTML pass-through disabled (escapes user content safely).
marked.setOptions({
  gfm: true,
  breaks: false,
});

const FRONTMATTER_RE = /^---\s*\n([\s\S]*?)\n---\s*\n([\s\S]*)$/;

function parseFrontmatter(raw: string): {
  meta: Omit<BlogPostMeta, 'slug' | 'readingTime'>;
  body: string;
} {
  const match = FRONTMATTER_RE.exec(raw);
  if (!match) {
    throw new Error(
      `Blog post is missing frontmatter. Expected '---\\nkey: value\\n---\\nbody'.`,
    );
  }

  const [, fmBlock, body] = match;
  const meta: Record<string, unknown> = {};
  for (const line of fmBlock.split('\n')) {
    const m = /^([a-zA-Z_]+):\s*(.*)$/.exec(line);
    if (!m) continue;
    const [, key, raw] = m;
    let value: unknown = raw;
    if (raw.startsWith('[') && raw.endsWith(']')) {
      value = raw
        .slice(1, -1)
        .split(',')
        .map((s) => s.trim().replace(/^["']|["']$/g, ''))
        .filter(Boolean);
    } else if (/^["'].*["']$/.test(raw)) {
      value = raw.slice(1, -1);
    } else if (raw === 'true' || raw === 'false') {
      value = raw === 'true';
    }
    meta[key] = value;
  }

  const validated: Omit<BlogPostMeta, 'slug' | 'readingTime'> = {
    title: String(meta.title ?? ''),
    description: String(meta.description ?? ''),
    date: String(meta.date ?? ''),
    tags: Array.isArray(meta.tags) ? (meta.tags as string[]) : [],
    author: String(meta.author ?? 'Andrés Morales'),
    coverImage: meta.coverImage ? String(meta.coverImage) : undefined,
    coverImageCredit: meta.coverImageCredit
      ? String(meta.coverImageCredit)
      : undefined,
    coverImageAlt: meta.coverImageAlt ? String(meta.coverImageAlt) : undefined,
    draft: meta.draft === true || meta.draft === 'true',
    source: meta.source ? String(meta.source) : undefined,
    sourceTitle: meta.sourceTitle ? String(meta.sourceTitle) : undefined,
    generatedBy: meta.generatedBy ? String(meta.generatedBy) : undefined,
  };

  if (!validated.title || !validated.date) {
    throw new Error(
      `Blog frontmatter missing required fields. Got: ${JSON.stringify(meta)}`,
    );
  }

  return { meta: validated, body };
}

function estimateReadingMinutes(body: string): number {
  // ~200 wpm; minimum 1 minute.
  const words = body.trim().split(/\s+/).length;
  return Math.max(1, Math.round(words / 200));
}

function fileFor(slug: string, locale: BlogLocale): string | null {
  // Try locale-specific file first.
  const localized = join(CONTENT_DIR, `${slug}.${locale}.md`);
  if (existsSync(localized)) return localized;
  // Fall back to English if a localized variant isn't published yet.
  if (locale !== 'en') {
    const fallback = join(CONTENT_DIR, `${slug}.en.md`);
    if (existsSync(fallback)) return fallback;
  }
  return null;
}

/**
 * Last-modified timestamp for a (slug, locale) post. Uses the source
 * file's mtime, falling back to the en file's mtime when the locale
 * variant is missing (en is the canonical body for fallback). Returns
 * `null` when neither file exists.
 *
 * Used by the sitemap to give Google a real `lastmod` per post instead
 * of `new Date()` (which would lie to crawlers and devalue the
 * `lastmod` signal for SEO).
 */
export function postMtime(slug: string, locale: BlogLocale): Date | null {
  for (const loc of locale === 'en' ? ['en'] : [locale, 'en']) {
    const f = join(CONTENT_DIR, `${slug}.${loc}.md`);
    if (existsSync(f)) {
      try {
        return statSync(f).mtime;
      } catch {
        return null;
      }
    }
  }
  return null;
}

function loadPost(slug: string, locale: BlogLocale): BlogPost | null {
  const file = fileFor(slug, locale);
  if (!file) return null;

  const raw = readFileSync(file, 'utf-8');
  const { meta, body } = parseFrontmatter(raw);
  // Hide drafts from public reads. The autoblogging pipeline writes posts
  // to `content/blog/drafts/<slug>.<lang>.md` with `draft: true` in the
  // frontmatter so they don't leak into listing pages or `[slug]` routes
  // until Andrés promotes them to `content/blog/<slug>.<lang>.md` (or
  // removes the `draft:` flag from the published location).
  if (meta.draft) return null;
  const html = marked.parse(body) as string;

  return {
    ...meta,
    slug,
    locale,
    readingTime: estimateReadingMinutes(body),
    content: html,
    raw: body,
  };
}

function listAllSlugs(): string[] {
  if (!existsSync(CONTENT_DIR)) return [];
  const files = readdirSync(CONTENT_DIR);
  const slugs = new Set<string>();
  for (const f of files) {
    const m = /^(.+?)\.(en|es|pt)\.md$/.exec(f);
    if (m) slugs.add(m[1]);
  }
  return [...slugs];
}

/**
 * Slugs grouped by the locales where a translated body actually exists.
 * Used by the sitemap and `generateMetadata` so hreflang alternates only
 * advertise languages that have content — otherwise Google follows them
 * into 404s and reports "Page with redirect" / "Not found (404)" in GSC.
 */
export function listSlugsByLocale(): Record<BlogLocale, Set<string>> {
  const out: Record<BlogLocale, Set<string>> = {
    en: new Set(),
    es: new Set(),
    pt: new Set(),
  };
  if (!existsSync(CONTENT_DIR)) return out;
  for (const f of readdirSync(CONTENT_DIR)) {
    const m = /^(.+?)\.(en|es|pt)\.md$/.exec(f);
    if (!m) continue;
    out[m[2] as BlogLocale].add(m[1]);
  }
  return out;
}

/**
 * Returns the slugs that have a body in the requested locale.
 * (Used by `listPosts` so we don't show EN/PT posts on /es and vice-versa.)
 */
function listSlugsForLocale(locale: BlogLocale): string[] {
  if (!existsSync(CONTENT_DIR)) return [];
  const files = readdirSync(CONTENT_DIR);
  const slugs = new Set<string>();
  for (const f of files) {
    const m = new RegExp(`^(.+?)\\.${locale}\\.md$`).exec(f);
    if (m) slugs.add(m[1]);
  }
  return [...slugs];
}

/**
 * Returns the localized summaries of all posts that have a body in the
 * given locale, sorted newest first. Posts without a localized body are NOT
 * listed (instead they 404 on the detail page if visited directly).
 */
export function listPosts(locale: BlogLocale): BlogPostSummary[] {
  const slugs = listSlugsForLocale(locale);
  const posts: BlogPostSummary[] = [];
  for (const slug of slugs) {
    const post = loadPost(slug, locale);
    if (!post) continue;
    posts.push({
      slug: post.slug,
      title: post.title,
      description: post.description,
      date: post.date,
      tags: post.tags,
      readingTime: post.readingTime,
      author: post.author,
      coverImage: post.coverImage,
      coverImageCredit: post.coverImageCredit,
      coverImageAlt: post.coverImageAlt,
      href: `/${locale}/blog/${post.slug}`,
    });
  }
  posts.sort((a, b) => (a.date < b.date ? 1 : -1));
  return posts;
}

/**
 * Returns a single post by slug, in the requested locale (falling back to EN).
 */
export function getPost(
  slug: string,
  locale: BlogLocale,
): BlogPost | null {
  return loadPost(slug, locale);
}

/**
 * Returns all slugs known across all locales (used by `generateStaticParams`).
 */
export function listAllPostSlugs(): string[] {
  return listAllSlugs();
}

/**
 * Reads all draft posts from `content/blog/drafts/`. Drafts are posts the
 * news pipeline generated and is waiting for Andrés to approve. They have
 * `draft: true` in their frontmatter and live in a separate directory so
 * they don't mix with published content.
 *
 * Returns one entry per (slug × locale) pair found in drafts/.
 */
export function listDrafts(): BlogPostSummary[] {
  const draftsDir = join(CONTENT_DIR, 'drafts');
  if (!existsSync(draftsDir)) return [];
  const files = readdirSync(draftsDir);
  const seen = new Set<string>();
  const drafts: BlogPostSummary[] = [];
  for (const f of files) {
    const m = /^(.+?)\.(en|es|pt)\.md$/.exec(f);
    if (!m) continue;
    const slug = m[1];
    const locale = m[2] as BlogLocale;
    const key = `${slug}:${locale}`;
    if (seen.has(key)) continue;
    seen.add(key);
    const file = join(draftsDir, f);
    const raw = readFileSync(file, 'utf-8');
    const { meta, body } = parseFrontmatter(raw);
    drafts.push({
      slug,
      locale,
      title: meta.title,
      description: meta.description,
      date: meta.date,
      tags: meta.tags,
      author: meta.author,
      readingTime: estimateReadingMinutes(body),
      coverImage: meta.coverImage,
      coverImageCredit: meta.coverImageCredit,
      coverImageAlt: meta.coverImageAlt,
      draft: meta.draft,
      source: meta.source,
      sourceTitle: meta.sourceTitle,
      generatedBy: meta.generatedBy,
      href: `/drafts/${locale}/${slug}`,
      draftPath: `content/blog/drafts/${slug}.${locale}.md`,
    });
  }
  // Newest first.
  drafts.sort((a, b) => (a.date < b.date ? 1 : -1));
  return drafts;
}

/**
 * Returns the path of a single draft file (used by the approve flow).
 */
export function draftPath(slug: string, locale: BlogLocale): string | null {
  const draftsDir = join(CONTENT_DIR, 'drafts');
  const file = join(draftsDir, `${slug}.${locale}.md`);
  return existsSync(file) ? file : null;
}

/**
 * Promotes a draft to a published post by moving it from
 * `content/blog/drafts/` to `content/blog/`. Removes the `draft: true`
 * flag from the frontmatter so the post is immediately visible on the
 * site after the next build.
 *
 * Used by the autoblogging approve flow (manual or via a Telegram
 * command).
 */
export function promoteDraft(
  slug: string,
  locale: BlogLocale,
): { ok: true; publishedPath: string } | { ok: false; reason: string } {
  const draftsDir = join(CONTENT_DIR, 'drafts');
  const src = join(draftsDir, `${slug}.${locale}.md`);
  if (!existsSync(src)) {
    return { ok: false, reason: `No draft found at ${src}` };
  }
  const raw = readFileSync(src, 'utf-8');
  // Strip `draft: true` (and any orphan `draft: false`) so the post is
  // picked up by `loadPost`.
  const updated = raw.replace(/^draft:\s*(true|false)\s*\n/m, '');
  const dst = join(CONTENT_DIR, `${slug}.${locale}.md`);
  // If the published version already exists, refuse — Andrés should
  // delete it first if he wants to overwrite.
  if (existsSync(dst)) {
    return {
      ok: false,
      reason: `Published post already exists at ${dst}. Delete it first if you want to overwrite.`,
    };
  }
  // Write to published location, then remove draft.
  require('node:fs').writeFileSync(dst, updated, 'utf-8');
  require('node:fs').unlinkSync(src);
  return { ok: true, publishedPath: dst };
}
